import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { globSync } from 'node:fs';

// Multi-page static site. Every HTML file is an entry point; Vite rewrites the
// asset URLs inside them and emits hashed, minified CSS/JS into dist/.
// Files under public/ are copied verbatim, so /assets/... URLs keep working.
//
// Everything under blog/, wiki/ and day/ is generated by build/site.js, which
// predev and prebuild run first — so the glob below always sees current pages.
// Don't add entries by hand; add a Markdown file to content/ instead.
const pages = [
  'index.html',
  '404.html',
  ...globSync('{blog,wiki,day}/**/index.html', { cwd: import.meta.dirname }),
];

export default defineConfig({
  appType: 'mpa',
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    assetsInlineLimit: 0,
    rollupOptions: {
      input: Object.fromEntries(pages.map((p) => [p.replace(/\/?index\.html$/, '') || 'home', resolve(import.meta.dirname, p)])),
    },
  },
});
